name: Update

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# KUDOS to this awesome page for explaining a simple method for a dynamic matrix:
# https://brunoscheufler.com/blog/2021-10-09-generating-dynamic-github-actions-workflows-with-the-job-matrix-strategy

jobs:
  update_model_list:
    name: "Update model list"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install dependencies
        run: poetry install --only main

      - name: Get the latest models
        run: poetry run update_models
        env:
          PYTHONUNBUFFERED: 1

      - name: Commit and push if it changed
        run: |-
          git config user.name "Major Hayden"
          git config user.email "major@mhtx.net"
          git add output
          timestamp=$(date -u)
          git commit -m "Auto-update: ${timestamp}" || exit 0
          git pull --rebase
          git push

      - name: Generate a list of models for the actions matrix
        id: set-matrix
        run: |
          export MODELS=$(jq -cr "[.[].modelCode]" output/models.json | sed 's/\"/\\"/g')
          echo "::set-output name=matrix::{\"models\":$MODELS}"

  update_each_model:
    name: "Update each model"
    needs: update_model_list
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix: ${{fromJSON(needs.update_model_list.outputs.matrix)}}
    steps:
      - name: Check environment
        run: |
          env | sort
